---
title: "R Notebook: Make out-in-out files from WB data"
output: html_notebook
---

```{r get organized}
#Set up the environment for TSINFO3
.libPaths("C:/R/libs")
#add the libraries
library(dplyr)
#library(MuMIn)
#library(pastecs)

#specify the working directory
setwd("Z:/Informatics/S031/analyses/wb/out-in-out")

#choose (un-comment) the appropriate weigbhridge csv created by foxpro
#avidsum <- read.csv("Z:/Informatics/S031/analyses/wb/weight algorithms/wb2_and_3/1617/wbdata_1617_pred_wts.csv", header = TRUE, sep=",", dec= ".")
#avidsum <- read.csv("Z:/Informatics/S031/analyses/wb/weight algorithms/wb2_and_3/1718/wbdata_1718_pred_wts.csv", header = TRUE, sep=",", dec= ".")
#avidsum <- read.csv("Z:/Informatics/S031/analyses/wb/weight algorithms/wb2_and_3/1819/wbdata_1819_pred_wts.csv", header = TRUE, sep=",", dec= ".")
avidsum <- read.csv("Z:/Informatics/S031/analyses/wb/weight algorithms/wb2_and_3/1920/wbdata_1920_pred_wts.csv", header = TRUE, sep=",", dec= ".")

#choose the name of the correct nest file:
#nestfile<-"Z:/Informatics/S031/S0311617/croz1617/wb/wb_nests_1617.csv"
#nestfile<-"Z:/Informatics/S031/S0311718/croz1718/wb/wb_nests_1718.csv"
#nestfile<-"Z:/Informatics/S031/S0311819/croz1819/wb/wb_nests_1819.csv"
nestfile<-"Z:/Informatics/S031/S0311920/croz1920/wb/wb_nests_1920.csv"


#so you don't have to scroll all the way to bottom to change the name of the final product (but you do need to change it here):
#onofile<-"ono_1617.csv"
#onofile<-"ono_1718.csv"
#onofile<-"ono_1819.csv"
onofile<-"ono_1920.csv"

#filter data for just PIT-tagged birds     
avidsum_filt <- filter(avidsum, avid!=9999)

#convert datetime1 to a date time field in the correct timezone
avidsum_filt$datetime1 <- as.POSIXct(avidsum_filt$datetime1,format="%m/%d/%Y %H:%M:%S", tz="Pacific/Auckland")

nrow(avidsum_filt)

```


```{r add nest numbers and evaluate whether there are mis-labeled directions}
#who was mated to who - check the WB_breeders tables in the yearly 
#directories; something like if two crossings in same direction
#check to see if mate crossed between them?
#mate1 - in
#mate2 - out
#mate2 - in
#mate1 - in ##this one is probably an out?
#mate2 - out

#Get nest for the year using the "wb_breeders" files (nestfile var is set above)
mates<-read.csv(nestfile, header = TRUE, sep=",", dec= ".")%>%
    rename_all(tolower)
mates$avid<-as.numeric(as.character(mates$avid))

nests<-select(mates,avid,nest)

#join the nest numbers
avidsum_filt<-left_join(avidsum_filt,nests)

#so now avidsum_sort has nest numbers in it  sort on nest number, date to see if there are suspiscious directions
avidsum_nsort<-avidsum_filt[order(avidsum_filt$nest,avidsum_filt$datetime1),]
#add a date column
avidsum_nsort$date<-as.POSIXct(strptime(avidsum_nsort$datetime1, "%Y-%m-%d", tz="Pacific/Auckland"))

#write.csv(avidsum_nsort, "avidsum_nsort.csv")
#looking at that file it is very difficult to tell if there are mis-attributed directions
#attempt to scan visually by ploting the sequences


#Code based on Annie's prior work on this:
# Construct attendance patterns by nest ####

# consider removing xings that were less than 5 min apart?

# Function for plotting attendence pattern by nest
#num = nest number
#file = avidsum_nsort
nest_attend <- function(num, file, startdate, enddate, coltext){
  dates <- as.POSIXct(strptime(seq.Date(from=as.Date(startdate),to=as.Date(enddate), by=1), "%Y-%m-%d", tz="Pacific/Auckland"))
  wb <- file%>%
    filter(nest==num, date%in%dates)
  par(las=1)
  plot(wb$datetime1,as.numeric(wb$avid), type="l", pch=19, xaxt="n",yaxt="n",ylab="", xlab="Date", 
       main=paste("wb",num, sep=""), col="lightgrey", xlim=c(min(dates),(max(dates)+86400)))
  axis(1, at=dates, labels=dates)
  axis(2, at=wb$avid, labels=wb$avid)
  calibrate::textxy(wb$datetime1,as.numeric(wb$avid), labs=wb$direction, cex=0.75, col=coltext,offset=0)
  calibrate::textxy(wb$datetime1[wb$direction=="unk"],as.numeric(wb$avid[wb$direction=="unk"]), labs=wb$direction, cex=0.75, col="red",offset=0)
}


par(mfrow=c(4,2), mar=c(2,5,2,2),oma=c(5,3,3,3), las=1)

#set dates according to season:
startdate = "2019-12-21"
enddate = "2020-01-01"
# loop to plot all nests
for(i in 1:max(avidsum_nsort$nest,na.rm=TRUE)){
  nest_attend(i,avidsum_nsort, startdate, enddate, coltext = "blue")
    }

```


```{r add daysbtwn}
#add the daysbtwn column - the number of days between two crossings

#Re-sort on just avid and datetime1
avidsum_sort<-avidsum_filt[order(avidsum_filt$avid,avidsum_filt$datetime1),]

#initialize the column in correct format (numeric):
avidsum_sort$daysbtwn<-as.numeric(difftime(avidsum_sort$datetime1[2],avidsum_sort$datetime1[2],units="days"))

#Loop through datafame and add values for daysbtwn as appropriate
i=1
while (i<nrow(avidsum_sort)) {
        mid <- avidsum_sort$avid[i] #first avid
        dt1 <- avidsum_sort$datetime1[i] #the time of the first crossing
        md <- avidsum_sort$direction[i] #the direction of the first crossing
    
        while(avidsum_sort$avid[i]==mid){ #for this tag
        i<-i+1 #check the next row
        
        if (i<nrow(avidsum_sort)) {
            if (avidsum_sort$avid[i] == mid & avidsum_sort$direction[i]!=md) {
              #update daysbtwn - in days - if next crossing is same bird
              #and opposite direction
              avidsum_sort$daysbtwn[i] <-as.numeric (difftime(avidsum_sort$datetime1[i],dt1,units="days"))
              dt1 <- avidsum_sort$datetime1[i]
              md <- avidsum_sort$direction[i]
              }
            #reset date and direction vars to those of the current row
            else {
                dt1 <- avidsum_sort$datetime1[i]
                md <- avidsum_sort$direction[i]
            }
        } else {
            break
        }
    } 
    #Onto the next tag
}

summary(avidsum_sort$daysbtwn)


```

```{r create out-in-out format}
#Make a dataframe that has one row for each sequence of 3 crossings for each individual.

db <- avidsum_sort
db$direction<-as.character(db$direction)
db$wt1<-0
db$wt2<-0
db$wt3<-0
db$dir1<-as.character(".")
db$dir2<-as.character(".")
db$dir3<-as.character(".")
db$duration1<-0
db$duration2<-0
db$duration3<-0
db$date1<-as.POSIXct(NA,format="%m/%d/%Y %H:%M:%S", tz="Pacific/Auckland")
db$date2<-as.POSIXct(NA,format="%m/%d/%Y %H:%M:%S", tz="Pacific/Auckland")
db$date3<-as.POSIXct(NA,format="%m/%d/%Y %H:%M:%S", tz="Pacific/Auckland")

i<-1
while(i<nrow(db)-2) {
    mid<-db$avid[i]
    while(db$avid[i]==mid & i<nrow(db)-2){ #for this tag
        if(db$avid[i+2]==mid & i<nrow(db)-2) { #three in a row same id
            db$wt1[i]<-db$pred_wt[i]
            db$wt2[i]<-db$pred_wt[i+1]
            db$wt3[i]<-db$pred_wt[i+2]
            db$dir1[i]<-db$direction[i]
            db$dir2[i]<-db$direction[i+1]
            db$dir3[i]<-db$direction[i+2]
            db$duration1[i]<-db$daysbtwn[i]
            db$duration2[i]<-db$daysbtwn[i+1]
            db$duration3[i]<-db$daysbtwn[i+2]
            db$date1[i]<-db$datetime1[i]
            db$date2[i]<-db$datetime1[i+1]
            db$date3[i]<-db$datetime1[i+2]
            i<-i+1
        } else {
            i<-i+1    
            }
        }
}

#add var durout1i - the duration of the foraging trip in hours
db$durout1i<-db$duration2*24

#add var foodload - the difference between the in weight and the second out weight
db$foodload<-db$wt2-db$wt3

#retain only the records where the sequence out-in-out is preserved
ono<-filter(db,dir1=="out" & dir2=="in" & dir3=="out")

#make the csv file
write.csv(ono, onofile)     

```

